name: Bug report
description: Create a bug report for this mod.
title: "[vX.X+loader-1.X.X] Bug report name"
labels: ["Bug"]
assignees: []
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to fill out this bug report!
  - type: markdown
    attributes:
      value: |
        **Note:** Issue titles start with the square brackets that contain the full mod version.  
        **Format:** v[mod_version]+[mod_loader]-[minecraft_version]  
        **Example: v1.0+fabric-1.20**
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Please describe what happened, aka the bug or issue you encountered.
      placeholder: Describe the issue here!
      value: "When doing something expecting X to happen, I got Y instad."
    validations:
      required: true
  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to reproduce
      description: If applicable, please list the steps to reproduce the issue.
      placeholder: List steps to reproduce here!
      value: |
        1. Go to...
        2. Then do...
        3. See the bug or issue or a crash
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output or crash report
      description: |
        Please copy and paste any relevant log outputs or crash reports here.  
        Alternatively, you can publish the crash report to [Crashy](https://crashy.net/) and link it here.
      render: shell
  - type: textarea
    id: other-mods
    attributes:
      label: Other installed mods
      description: If applicable, please list all other mods you have installed alongside this one.
      placeholder: List other installed mods here, or "N/A" if you don't have any other mods installed.
      value: |
        1. First mod's name
        2. Second mod's name
        3. And so on... If you use a mod pack instead, state that and name the mod pack.
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: "By submitting this issue, you agree to the following:"
      options:
        - label: I agree that if the issue is regarding a crash, I gave the logs and the crash report.
          required: true
        - label: I agree that I will be available later for any follow-up questions to help diagnose and resolve the issue.
          required: true
